name: Publish to TestPyPI

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip setuptools wheel twine

      - name: Build source distribution
        run: python3 setup.py sdist

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@v1.8.10
        with:
          repository-url: https://test.pypi.org/project/hutoken
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
